version: '3'

services:
  es1:
    image: elasticsearch:8.11.1
    environment:
      - discover=single-node
    volumes:
      - $(pwd)/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - els
  
  grafana:
    image: grafana:latest
    container_name: graf
    ports:
      - "3001:3000"
    networks:
      - els
  
  kibana:
    image: kibana:8.11.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://es1:9200
    depends_on:
      - es1
    networks:
      - els
    
  golang-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: golang-app
    ports:
      - 9000:9000
    depends_on:
      - es1
    networks:
      - els

networks:
  els:
    driver: bridge